post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        # You can remove unused permissions here
        # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
        # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          ## dart: PermissionGroup.calendar
          'PERMISSION_EVENTS=0',
          ## dart: PermissionGroup.reminders
          'PERMISSION_REMINDERS=0',
          ## dart: PermissionGroup.contacts
          'PERMISSION_CONTACTS=0',
          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=0',
          ## dart: PermissionGroup.microphone
          'PERMISSION_MICROPHONE=0',
          ## dart: PermissionGroup.speech
          'PERMISSION_SPEECH_RECOGNIZER=0',
          ## dart: PermissionGroup.photos
          'PERMISSION_PHOTOS=0',
          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          'PERMISSION_LOCATION=1',
          ## dart: PermissionGroup.notification
          'PERMISSION_NOTIFICATIONS=1',
          ## dart: PermissionGroup.mediaLibrary
          'PERMISSION_MEDIA_LIBRARY=1',
          ## dart: PermissionGroup.sensors
          'PERMISSION_SENSORS=0',
          ## dart: PermissionGroup.bluetooth
          'PERMISSION_BLUETOOTH=0',
          ## dart: PermissionGroup.appTrackingTransparency
          'PERMISSION_APP_TRACKING_TRANSPARENCY=10',
          ## dart: PermissionGroup.criticalAlerts
          'PERMISSION_CRITICAL_ALERTS=0',
      